### ISSUE TITLE
값 수신 문제

### ISSUE THREAD

**Issue by jihoonkimtech** [SangUk-Jeon/Bluetooth_Example#1]
상욱 학생 레포지토리 잘 구경 했습니다.

https://github.com/SangUk-Jeon/Bluetooth_Example/blob/a52214d2133555588124d3770b064113d773e3aa/Bluetooth_Example.ino#L1
해당 코드는 블루투스 수신 데이터를 받아 정수형 변수인 value에 저장하는 역할을 수행합니다.
그런데, 역설적이게도 코드의 위치가 전역 위치에 있어  블루투스 통신 시작 전에 초기 1번만 실행되어 제대로 동작하지 않을 것으로 예측됩니다.

해당 코드의 문제 해결이 필요합니다~
문제 해결 후 코멘트 달고 Close issue 부탁드립니다.

**Comment by SangUk-Jeon** [comment]
int value = Serial.read(); 를 void loop() 함수에 넣어줬습니다.
